### ISSUE TITLE
User Story 1: Pokémon Card List

### ISSUE THREAD

**Issue by FlorianNova** [FlorianNova/PokeTeam_PokeCompare#1]
## Value Proposition:
As a User, I want to view a comprehensive list of Pokémon with their names, numbers, and pictures, presented as individual cards, to easily browse and familiarize myself with all the Pokémon available in the app.

## Description:
The PokéTeam web app aims to present a user-friendly and visually appealing pattern list that showcases all Pokémon from the PokeAPI. Each Pokémon will be displayed as a card, featuring its name, number, and picture.

![Bildschirmfoto 2023-07-19 um 16 03 55](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/715cc941-017b-4953-9f3a-77816913216d)

## Acceptance Criteria:

- [ ] The user interface exhibits a card pattern list displaying all Pokémon, with their names, numbers, and pictures, sourced from the PokeAPI.
- [ ] The list is scrollable, allowing users to access additional Pokémon cards beyond the visible area.
- [ ] The layout follows a pattern (e.g. 3x5) to display the Pokémon cards.

## Tasks:

- [ ] Create a new branch named "feature/pokemonlist."
- [ ] Implement the Pokémon fetched from the PokeAPI.
- [ ] Design and develop a PokemonCard component specifically for displaying individual Pokémon list entries.
- [ ] Style the Pokémon cards according to the provided guidelines and the previous project for inspiration (https://codesandbox.io/s/react-effects-and-fetch-pokemon-api-with-paging-version-2-0-yw68ny).

**Comment by FlorianNova** [comment]
![Bildschirmfoto 2023-07-19 um 13 32 22](https://github.com/FlorianNova/PokeTeam_PokeInterplay/assets/133348117/00ad335b-c733-449b-970c-2d98fbb4c92d)

**Comment by FlorianNova** [comment]
![Bildschirmfoto 2023-07-19 um 13 33 41](https://github.com/FlorianNova/PokeTeam_PokeInterplay/assets/133348117/c6b62f25-6017-430a-a01c-be135591cc65)

**Comment by FlorianNova** [comment]
![Bildschirmfoto 2023-07-19 um 13 34 29](https://github.com/FlorianNova/PokeTeam_PokeInterplay/assets/133348117/ecf1b8a7-d4b9-41fa-8957-7a93fa86beec)

**Comment by FlorianNova** [comment]
![Bildschirmfoto 2023-07-19 um 14 11 16](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/c59e4001-3f68-41bd-a795-5d235350b8a5)

**Comment by FlorianNova** [comment]
number and name is written below the picture of the Pokemon.

**Comment by FlorianNova** [comment]
![Bildschirmfoto 2023-07-19 um 14 28 33](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/ee97c68d-6af5-4801-bda5-a02560ff4403)

**Comment by FlorianNova** [comment]
number and name is written below the picture of the Pokemon.

**Comment by actyvystom** [comment]
A nice first one! 👍🏻 
See some comments:
- your **value proposition** should not contain technical terms like 'grid pattern list'
- a goal is missing on the value proposition (in order to/so that), I suggest to add it e.g. 
>  As a User, I want to see all Pokémon displayed with their name, number and picture
> in order to get an overview of all pokemon featured in the app

You should add a bit more detail to your **acceptance criteria**, e.g. _the list should be scrollable if there are items below the fold_ 

In your **task list**, I suggest to add some `PokemonCard` component which will be explicitly created to display your Pokemon list entries.
Additionally you should adjust the name of the branch you are going to create for that feature as "create Pokemon list" is not a valid branch name. Better use something like e.g. `feature/pokemonlist`

**Comment by actyvystom** [comment]
LGTM 🚀
