### ISSUE TITLE
User Story 4: Pokémon Details 

### ISSUE THREAD

**Issue by FlorianNova** [FlorianNova/PokeTeam_PokeCompare#17]
# User Story 4: Pokémon Details 
### Value Proposition:
**As a User**,
**I want to** be able to click a Pokémon 
**so i can** see the details of the Pokemon.
### Description:
Users can click on Pokemon to expand the Card and show some Details, clicking again will close the card.

![Screenshot 2023-08-09 at 16 20 10](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/1ad60b95-dac1-48b9-9ee4-cb4870e6f3fb)
![Screenshot 2023-08-09 at 16 23 37](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/4bfb57eb-2d31-45b8-967d-d9b1a70ff91b)

### Acceptance Criteria:

- [ ] Users must be able to click a Pokemon to expand the Card.
- [ ] Card must contain Details about Pokemon.
- [ ] Details only shown on expanded Cards.

### Tasks:
- [ ] fetch Pokemon Details
- [ ] add Pokemon Details to Pokemon Card
- [ ] show Pokemon Details if Pokemon is clicked (expand Card)
