### ISSUE TITLE
User Story 3.1: Pokémon Team Selection

### ISSUE THREAD

**Issue by FlorianNova** [FlorianNova/PokeTeam_PokeCompare#4]
## User Story 3.1: Pokémon Team Selection
**As a user**, 
**I want to** have the ability to choose a minimum of 1 and a maximum of 6 Pokémon from the list, 
**so i can** add them to a Team in the Pokemon Team page following later.

## Description:

![Bildschirmfoto 2023-07-20 um 12 28 44](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/de0db728-1ac5-4a37-8c7a-2e53d93dc649)

## Acceptance Criteria:
- [ ] The user interface should allow users to select Pokémon from the displayed list.
- [ ] The team selection should enforce the limit of 1 to 6 Pokémon for each team.
- [ ] Selected Pokémon should be marked / highlighted.

## Tasks:

- [ ] Implement option to select a minimum of 1 and a maximum of 6 Pokémon.
- [ ] Selected Pokémon are marked / highlighted.

**Comment by josch87** [comment]
I'm not quite sure if this US already gives more value to the user. The user can only select the items but can not do anything with the selection (like store it into a state). I have seen that you were splitting up user story 3 into multiple user stories. Usually these would be tasks in one user story I think.
