### ISSUE TITLE
User Story 3.3: Pokémon Team Saving

### ISSUE THREAD

**Issue by FlorianNova** [FlorianNova/PokeTeam_PokeCompare#6]
## User Story 3.3: Pokémon Team Saving
**As a user**, 
**I want to** be able to save my selected Pokémon team under a custom name, 
**so i can** store multiple teams for future reference.

## Description:
![Bildschirmfoto 2023-07-20 um 12 50 29](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/dc5c8d79-a26a-444a-aa11-a2399acf9a64)

## Acceptance Criteria:
- [ ] There is a clear and intuitive process for saving the selected team under a custom name (e.g., Team 1).

## Task:
- [ ]  Implement the save functionality, allowing users to give the Team a name. (Text input) (Save Button)
- [ ] use local storage as storage solution
