### ISSUE TITLE
User Story 3.5: Team Deletion

### ISSUE THREAD

**Issue by FlorianNova** [FlorianNova/PokeTeam_PokeCompare#8]
## User Story 3.5: Team Deletion
**As a user**,
**I want to** I want the ability to delete saved Pokémon teams from the Teams page,
**so i can** delete them if i want delete them.

## Description:

![Bildschirmfoto 2023-07-20 um 13 53 56](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/4599b44a-bca6-4538-98a6-f7b038e392a4)

## Acceptance Criteria:
- [ ] Users should be able to delete specific saved Pokémon teams from the Teams page.

## Tasks:
- [ ]   Implement a deletion functionality to allow users to remove specific saved Pokémon teams.
- [ ] Add a confirmation prompt to prevent accidental deletions.
