### ISSUE TITLE
User Story 3.6: Pokémon Team Scrolling Navigation

### ISSUE THREAD

**Issue by FlorianNova** [FlorianNova/PokeTeam_PokeCompare#9]
## User Story 3.6: Pokémon Team Scrolling Navigation

**As a user**, 
**I want to** have a simple and intuitive way to navigate through all my saved Pokémon teams by scrolling down the page.Eeach team should be presented one after the other, 
**so i can** access each team without the need for complex interactions.

## Description:
![Bildschirmfoto 2023-07-20 um 14 35 53](https://github.com/FlorianNova/PokeTeam_PokeCompare/assets/133348117/b05038a2-f428-4edb-aa92-52c6e15ddc1f)

## Acceptance Criteria:

- [ ] The app should display all saved Pokémon teams in a vertical arrangement, one after the other, on the same page.
- [ ] As I scroll down the page, each team should be automatically presented in the order they were saved.

## Tasks:

- [ ] Let each saved Pokémon team be listed in a list, one after the other.
